# Generated by Django 5.0.6 on 2024-07-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categoriaS',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_unico', models.IntegerField(default=None, unique=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('precio', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now_add=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendita.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productoS',
            },
        ),
    ]
